AllCops:
  TargetRubyVersion: 2.7
  Include:
    - 'lib/**/*'
    - 'spec/**/*'
  NewCops: enable

Layout/LineLength:
  Max: 120

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false # enable when Ruby 2.7 is min. supported version

Style/BlockDelimiters:
  Enabled: false

Style/CollectionCompact:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/ExpandPathArguments:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MutableConstant:
  Enabled: true

Style/MissingRespondToMissing:
  Enabled: false

Style/NegatedIfElseCondition:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/SwapValues:
  Enabled: true
